import os

INGREDIENTS_DICT = {
    "Cucumber": "🥒",
    "Pasta": "🍝",
    "Canned olives": "🫒",
    "Bell peppers": "🫑",
    "Tomatoes": "🍅",
    "Tomato sauce": "🍅",
    "Olive oil": "🫒",
    "Garlic": "🧄",
    "Salt": "🧂",
    "Pepper": "🧂",
    "Chicken": "🍗",
    "Chicken broth": "🍗",
    "Cumin": "🧂",
    "Lentils": "🫐",
    "Onions": "🧅",
    "Eggs": "🥚",
    "Flour": "🌾",
    "Sugar": "🧂",
    "Milk": "🥛",
    "Baking powder": "🧂",
    "Butter": "🧈",
    "Cinnamon": "🧂",
    "Oats": "🌾",
    "Apple sauce": "🍎",
    "Chocolate chips": "🍫",
    "Dried herbs": "🌿",
    "Rice": "🍚",
    "Canned beans": "🫐",
    "Salmon": "🐟",
    "Honey": "🍯",
    "Soy sauce": "🧂",
    "Balsamic vinegar": "🧂",
    "Peanut butter": "🥜",
    "Jelly": "🍇",
    "Bananas": "🍌",
    "Bread": "🍞",
    "Mustard": "🧂",
    "Mayonnaise": "🧂",
    "Ketchup": "🧂",
    "Pickles": "🧂",
    "Cheese": "🧀",
    "Potatoes": "🥔",
    "Coffee": "☕",
    "Steak": "🥩",
    "Pork": "🥩",
    "Bacon": "🥓",
    "Sausage": "🥓",
    "Crackers": "🧂",
    "Coffee": "☕",
    "Tea": "🍵",
    "Tofu": "🥬",
    "Cereal": "🌾",
    "Yogurt": "🥛",
    "Sweet potatoes": "🥔",
}

INGREDIENTS_CSV_PATH = os.getcwd() + "/../datasets/recipes_dataset_v2.xlsx"